# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

# path to file that contains sample information 
samples: "data/samples_paired.tsv"
# path to folder that contains raw reads and reference files
data_folder: "data"
# path to folder where output of the pipeline will be saved
output_folder: "data/output"
# path to reference genome fasta file (including file prefix, excluding file suffix/extension)
reference: 
        # Currently has to end in .fa
        #genome: "data/S288C_reference_sequence_R64-2-1_20150113.correct_ids"
        #genome: "data/S288C_reference_sequence_R64-2-1_20150113"
        genome: "data/orf_coding_all_R64-2-1_20150113"
        gff: "data/saccharomyces_cerevisiae_R64-2-1_20150113_short.gff"
# htseq-count parameters
htseq-count:
        out: "data/output/htseq-count"
        stranded: "no"
        type: "gene"
        gene_id: "ID"
# trim galore parameters
trim_galore:
        out: "data/output/trims"
        phred_quality: "20"
# hisat2 parameters
hisat2:
        out: "data/output/hisat2"
# kallisto parameters
kallisto:
        out: "data/output/kallisto"
        bootstrap_samples: "60"
        # parameters for single end reads:
        # average fragment length
        avg_frag_len: ""
        # standard deviation of fragment length
        std_dev: ""
# deseq2 parameters
deseq2:
        # Output file if counts were provided by kallisto
        kal_out: "data/output/deseq2_kallisto_output.txt"
        # Output file if counts were provided by htseq-count
        htseq_out: "data/output/deseq2_htseq_output.txt"
        # Save MA-plot as PNG
        plot_ma: "data/output/deseq2_plotMA"
        # Save count plot as PNG
        plot_counts: "data/output/deseq2_plotCounts"
# sleuth parameters
sleuth:
        out: "data/output/sleuth"
        ensembl: "scerevisiae_gene_ensembl"
        n_genes: "20"
        p_val_cutoff: "0.05"
samtools:
        out: "data/output/samtools"
fastqc:
        pre_trim: "data/output/fastqc/pre_trim"
        post_trim: "data/output/fastqc/post_trim"
