suppressMessages({library("sleuth")})
tryCatch({
sample_id <- t(read.delim(file.path(snakemake@params["sample_tsv"]), header = TRUE, sep="\t")["sample"])
kal_dirs <- file.path(snakemake@params["kal_dirs"], sample_id)
print("Directories containing kallisto results: \n")
print(kal_dirs)
s2c <- read.table(file.path(snakemake@params["sample_condition"]), header = TRUE, sep = "\t", stringsAsFactors = FALSE)
print(s2c)
print("Appending kallisto result file paths")
s2c <- dplyr::mutate(s2c, path = kal_dirs)
print(s2c)
print("Generating sleuth object")
so <- sleuth_prep(s2c, extra_bootstrap_summary = TRUE)
print("Fitting full model")
so <- sleuth_fit(so, ~condition, 'full')
print("Fitting reduced model")
so <- sleuth_fit(so, ~1, 'reduced')
print("Likelihood ratio test for the models")
so <- sleuth_lrt(so, 'reduced', 'full')
sleuth_table <- sleuth_results(so, 'reduced:full', 'lrt', show_all = FALSE)
sleuth_significant <- dplyr::filter(sleuth_table, qval <= 0.05)
write(t(sleuth_significant), file = file.path(snakemake@params["outfile"]), sep = "\t")
}, error = traceback())
